<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPINHYDW0883" name="com.epam.scenarios.NewBusiness" tests="14" failures="0" timestamp="26 Sep 2017 09:19:16 GMT" time="603.482" errors="11">
  <testcase name="UpdateDrivers" time="0.000" classname="com.epam.scenarios.NewBusiness">
    <error type="java.lang.Throwable" message="Method NewBusiness.UpdateDrivers()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NewBusiness.UpdateDrivers()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.epam.driver.CoreDriverScript.executeTestCases(CoreDriverScript.java:270)
	at com.epam.driver.CoreDriverScript.main(CoreDriverScript.java:182)
]]>
    </error>
  </testcase> <!-- UpdateDrivers -->
  <testcase name="FillApplicantData" time="588.526" classname="com.epam.scenarios.NewBusiness">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="-1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.epam.businesslibs.ApplicantPage.FillApplicantAddressDetails(ApplicantPage.java:160)
	at com.epam.scenarios.NewBusiness.FillApplicantData(NewBusiness.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.epam.driver.CoreDriverScript.executeTestCases(CoreDriverScript.java:270)
	at com.epam.driver.CoreDriverScript.main(CoreDriverScript.java:182)
]]>
    </error>
  </testcase> <!-- FillApplicantData -->
  <testcase name="FillNewQuotePage" time="7.849" classname="com.epam.scenarios.NewBusiness"/>
  <testcase name="ViolationsPage" time="0.000" classname="com.epam.scenarios.NewBusiness">
    <error type="java.lang.Throwable" message="Method NewBusiness.ViolationsPage()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NewBusiness.ViolationsPage()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.epam.driver.CoreDriverScript.executeTestCases(CoreDriverScript.java:270)
	at com.epam.driver.CoreDriverScript.main(CoreDriverScript.java:182)
]]>
    </error>
  </testcase> <!-- ViolationsPage -->
  <testcase name="AddCoverages" time="0.000" classname="com.epam.scenarios.NewBusiness">
    <error type="java.lang.Throwable" message="Method NewBusiness.AddCoverages()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NewBusiness.AddCoverages()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.epam.driver.CoreDriverScript.executeTestCases(CoreDriverScript.java:270)
	at com.epam.driver.CoreDriverScript.main(CoreDriverScript.java:182)
]]>
    </error>
  </testcase> <!-- AddCoverages -->
  <testcase name="loginToMBGroup" time="5.582" classname="com.epam.scenarios.NewBusiness"/>
  <testcase name="ActionsonAdditionalInterest" time="0.000" classname="com.epam.scenarios.NewBusiness">
    <error type="java.lang.Throwable" message="Method NewBusiness.ActionsonAdditionalInterest()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NewBusiness.ActionsonAdditionalInterest()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.epam.driver.CoreDriverScript.executeTestCases(CoreDriverScript.java:270)
	at com.epam.driver.CoreDriverScript.main(CoreDriverScript.java:182)
]]>
    </error>
  </testcase> <!-- ActionsonAdditionalInterest -->
  <testcase name="GeneralInformationPage" time="0.000" classname="com.epam.scenarios.NewBusiness">
    <error type="java.lang.Throwable" message="Method NewBusiness.GeneralInformationPage()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NewBusiness.GeneralInformationPage()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.epam.driver.CoreDriverScript.executeTestCases(CoreDriverScript.java:270)
	at com.epam.driver.CoreDriverScript.main(CoreDriverScript.java:182)
]]>
    </error>
  </testcase> <!-- GeneralInformationPage -->
  <testcase name="SelectAgency" time="1.525" classname="com.epam.scenarios.NewBusiness"/>
  <testcase name="UpdateVehicals" time="0.000" classname="com.epam.scenarios.NewBusiness">
    <error type="java.lang.Throwable" message="Method NewBusiness.UpdateVehicals()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NewBusiness.UpdateVehicals()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.epam.driver.CoreDriverScript.executeTestCases(CoreDriverScript.java:270)
	at com.epam.driver.CoreDriverScript.main(CoreDriverScript.java:182)
]]>
    </error>
  </testcase> <!-- UpdateVehicals -->
  <testcase name="SubmissionsPage" time="0.000" classname="com.epam.scenarios.NewBusiness">
    <error type="java.lang.Throwable" message="Method NewBusiness.SubmissionsPage()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NewBusiness.SubmissionsPage()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.epam.driver.CoreDriverScript.executeTestCases(CoreDriverScript.java:270)
	at com.epam.driver.CoreDriverScript.main(CoreDriverScript.java:182)
]]>
    </error>
  </testcase> <!-- SubmissionsPage -->
  <testcase name="ActionsOnPremiumDetailsPage" time="0.000" classname="com.epam.scenarios.NewBusiness">
    <error type="java.lang.Throwable" message="Method NewBusiness.ActionsOnPremiumDetailsPage()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NewBusiness.ActionsOnPremiumDetailsPage()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.epam.driver.CoreDriverScript.executeTestCases(CoreDriverScript.java:270)
	at com.epam.driver.CoreDriverScript.main(CoreDriverScript.java:182)
]]>
    </error>
  </testcase> <!-- ActionsOnPremiumDetailsPage -->
  <testcase name="ActionsonUnderWritingPage" time="0.000" classname="com.epam.scenarios.NewBusiness">
    <error type="java.lang.Throwable" message="Method NewBusiness.ActionsonUnderWritingPage()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NewBusiness.ActionsonUnderWritingPage()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.epam.driver.CoreDriverScript.executeTestCases(CoreDriverScript.java:270)
	at com.epam.driver.CoreDriverScript.main(CoreDriverScript.java:182)
]]>
    </error>
  </testcase> <!-- ActionsonUnderWritingPage -->
  <testcase name="LoginAsUnderWriter" time="0.000" classname="com.epam.scenarios.NewBusiness">
    <error type="java.lang.Throwable" message="Method NewBusiness.LoginAsUnderWriter()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NewBusiness.LoginAsUnderWriter()[pri:0, instance:com.epam.scenarios.NewBusiness@1e4d3ce5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.epam.driver.CoreDriverScript.executeTestCases(CoreDriverScript.java:270)
	at com.epam.driver.CoreDriverScript.main(CoreDriverScript.java:182)
]]>
    </error>
  </testcase> <!-- LoginAsUnderWriter -->
</testsuite> <!-- com.epam.scenarios.NewBusiness -->
